import { describe, expect, it } from "vitest";
import { parseSubtitles, SubtitleParseError, validateCues } from "./vtt";

const VTT = `WEBVTT

00:12:14.120 --> 00:12:16.800
<v ALICE>So we walked down to Bath.

00:12:16.800 --> 00:12:20.150
<v ALICE>And then it rained.

00:12:22.900 --> 00:12:25.300
<v BOB>Did you?
`;

const SRT = `1
00:12:14,120 --> 00:12:16,800
So we walked down to Bath.

2
00:12:16,800 --> 00:12:20,150
And then it rained.
`;

describe("parseSubtitles — VTT", () => {
  it("reads times, text and speaker", () => {
    const cues = parseSubtitles(VTT);
    expect(cues).toHaveLength(3);
    expect(cues[0]).toEqual({
      start: 734.12,
      end: 736.8,
      text: "So we walked down to Bath.",
      speaker: "ALICE"
    });
    expect(cues[2].speaker).toBe("BOB");
  });

  it("skips the header and NOTE/STYLE/REGION blocks", () => {
    const cues = parseSubtitles(`WEBVTT

NOTE generated by minnty-dictate, whisper large-v3

STYLE
::cue { color: white }

00:00:01.000 --> 00:00:02.000
Only cue.
`);
    expect(cues).toHaveLength(1);
    expect(cues[0].text).toBe("Only cue.");
  });

  it("accepts a cue identifier before the timing line", () => {
    const cues = parseSubtitles(`WEBVTT

intro
00:00:01.000 --> 00:00:02.000
Text.
`);
    expect(cues[0].start).toBe(1);
  });

  it("ignores trailing cue settings on the timing line", () => {
    const cues = parseSubtitles(`WEBVTT

00:00:01.000 --> 00:00:02.000 align:start position:10%
Text.
`);
    expect(cues[0]).toMatchObject({ start: 1, end: 2, text: "Text." });
  });

  it("joins a multi-line cue into one line", () => {
    const cues = parseSubtitles(`WEBVTT

00:00:01.000 --> 00:00:02.000
<v ALICE>First part
second part
`);
    expect(cues[0].text).toBe("First part second part");
  });

  it("handles voice spans with classes and a closing tag", () => {
    const cues = parseSubtitles(`WEBVTT

00:00:01.000 --> 00:00:02.000
<v.loud ALICE>Shouting.</v>
`);
    expect(cues[0]).toMatchObject({ speaker: "ALICE", text: "Shouting." });
  });

  it("decodes character escapes in the payload", () => {
    const cues = parseSubtitles(`WEBVTT

00:00:01.000 --> 00:00:02.000
<v ALICE>Marks &amp; Spencer, 5 &lt; 6 &gt; 4.
`);
    expect(cues[0].text).toBe("Marks & Spencer, 5 < 6 > 4.");
  });

  it("decodes escapes in the speaker name too", () => {
    const cues = parseSubtitles(`WEBVTT

00:00:01.000 --> 00:00:02.000
<v A &amp; B>Text.
`);
    expect(cues[0].speaker).toBe("A & B");
  });

  it("decodes the ampersand last, so an escape cannot produce another", () => {
    const cues = parseSubtitles(`WEBVTT

00:00:01.000 --> 00:00:02.000
Literally &amp;lt; here.
`);
    expect(cues[0].text).toBe("Literally &lt; here.");
  });

  it("keeps escaped markup as text rather than stripping it", () => {
    const cues = parseSubtitles(`WEBVTT

00:00:01.000 --> 00:00:02.000
He wrote &lt;b&gt;bold&lt;/b&gt; in the chat.
`);
    expect(cues[0].text).toBe("He wrote <b>bold</b> in the chat.");
  });

  it("strips other inline markup", () => {
    const cues = parseSubtitles(`WEBVTT

00:00:01.000 --> 00:00:02.000
<v ALICE>A <b>bold</b> and <i>italic</i> word.
`);
    expect(cues[0].text).toBe("A bold and italic word.");
  });

  it("reads hours, and pads short fractions correctly", () => {
    const cues = parseSubtitles(`WEBVTT

01:00:00.5 --> 01:00:01.05
Text.
`);
    expect(cues[0].start).toBeCloseTo(3600.5, 3);
    expect(cues[0].end).toBeCloseTo(3601.05, 3);
  });

  it("accepts CRLF line endings and a BOM", () => {
    const cues = parseSubtitles("﻿WEBVTT\r\n\r\n00:00:01.000 --> 00:00:02.000\r\nText.\r\n");
    expect(cues).toHaveLength(1);
  });

  it("accepts MM:SS timestamps without an hours field", () => {
    const cues = parseSubtitles(`WEBVTT

12:14.120 --> 12:16.800
Text.
`);
    expect(cues[0].start).toBeCloseTo(734.12, 3);
  });
});

describe("parseSubtitles — SRT", () => {
  it("reads cues, with comma decimals and no speakers", () => {
    const cues = parseSubtitles(SRT);
    expect(cues).toHaveLength(2);
    expect(cues[0]).toEqual({ start: 734.12, end: 736.8, text: "So we walked down to Bath." });
    expect(cues[0].speaker).toBeUndefined();
  });
});

describe("parseSubtitles — rejection", () => {
  it("rejects a file with no cues", () => {
    expect(() => parseSubtitles("WEBVTT\n\nNOTE nothing here\n")).toThrow(SubtitleParseError);
  });

  it("rejects something that is not a subtitle file at all", () => {
    expect(() => parseSubtitles("ALICE: just a plain transcript\n")).toThrow(SubtitleParseError);
  });

  it("rejects a cue that ends before it starts", () => {
    expect(() =>
      parseSubtitles("WEBVTT\n\n00:00:05.000 --> 00:00:02.000\nBackwards.\n")
    ).toThrow(SubtitleParseError);
  });

  it("skips a cue with no text rather than emitting an empty one", () => {
    const cues = parseSubtitles(`WEBVTT

00:00:01.000 --> 00:00:02.000
<v ALICE>

00:00:03.000 --> 00:00:04.000
Real text.
`);
    expect(cues).toHaveLength(1);
    expect(cues[0].text).toBe("Real text.");
  });
});

describe("validateCues", () => {
  const cues = parseSubtitles(VTT);

  it("passes a well-formed file", () => {
    expect(validateCues(cues)).toEqual([]);
  });

  it("reports cues that run backwards", () => {
    const shuffled = [cues[1], cues[0]];
    expect(validateCues(shuffled)).toEqual([{ kind: "out-of-order", index: 1 }]);
  });

  it("reports overlapping cues", () => {
    const overlapping = [
      { start: 0, end: 5, text: "a" },
      { start: 3, end: 8, text: "b" }
    ];
    expect(validateCues(overlapping)).toEqual([{ kind: "overlap", index: 1 }]);
  });

  it("reports cues beyond the audio, which usually means mismatched files", () => {
    expect(validateCues(cues, 100)).toEqual([
      { kind: "beyond-audio", index: 0, audioDuration: 100 },
      { kind: "beyond-audio", index: 1, audioDuration: 100 },
      { kind: "beyond-audio", index: 2, audioDuration: 100 }
    ]);
  });

  it("does not complain when the audio is long enough", () => {
    expect(validateCues(cues, 1709.6)).toEqual([]);
  });
});
